# Generated by Django 4.1.5 on 2023-01-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', '-tag'], 'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
    ]
